# Installation

To download PyTorch, go to the link: https://pytorch.org/get-started/locally/

- select OS: Linux/ Mac/ Windows
- select Package: conda
- select Python 3.7

if Linux or Windows and want GPU support
- select Cuda version 10.2/ 11.3

Install Cuda Toolkit
Development environment for creating high performance GPU-accelerated applications
You need an NVIDIA GPU in your machine:

https://developer.nvidia.com/cuda-downloads

Legacy releases
11.0 update 2
select OS (e.g. Ubuntu)

Download and install

# Create conda environment and activate it 
`$ conda create -n pytorch python=3.7`

`$ conda activate pytorch`

# Install pytorch
`$ conda install pytorch torchvision -c pytorch`

or with GPU
`$ conda install pytorch torchvision cudatoolkit=11.3 -c pytorch`

In [1]:
# Installation Verification:
import torch

if torch.cuda.is_available():
    print(f"{torch.cuda.get_device_name(0)} is available for tensor operations!")
else:
    print("GPU is unavailable!")

NVIDIA GeForce GTX 1060 6GB is available for tensor operations!


# Tensor Basics

In [2]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher
# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(f"Scaler tensor: {x}")

x = torch.empty(3) # vector, 1D
print(f"Vector tensor: {x}")

x = torch.empty(2,3) # matrix, 2D
print(f"Matrix tensor: {x}")

x = torch.empty(2,2,3) # tensor, 3 dimensions

y = torch.empty(2,2,2,3) # tensor, 4 dimensions

print(f"Tensor with 3 dimensions: {x}")
print(f"Tensor with 4 dimensions: {y}")

Scaler tensor: tensor([1.8563e-25])
Vector tensor: tensor([1.7830e+25, 3.0952e-41, 1.8563e-25])
Matrix tensor: tensor([[1.7841e+25, 3.0952e-41, 1.7841e+25],
        [3.0952e-41, 2.9646e+35, 6.7305e+22]])
Tensor with 3 dimensions: tensor([[[1.8563e-25, 4.5642e-41, 1.8563e-25],
         [4.5642e-41, 4.4842e-44, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00, 1.7837e+25],
         [3.0952e-41, 1.7841e+25, 3.0952e-41]]])
Tensor with 4 dimensions: tensor([[[[1.7841e+25, 3.0952e-41, 1.7828e+25],
          [3.0952e-41, 4.4842e-44, 0.0000e+00]],

         [[1.5835e-43, 0.0000e+00, 1.7841e+25],
          [3.0952e-41, 1.8563e-25, 4.5642e-41]]],


        [[[3.3631e-44, 0.0000e+00, 4.4571e-26],
          [4.5642e-41, 1.4013e-45, 0.0000e+00]],

         [[4.4813e-26, 4.5642e-41, 1.9618e-44],
          [0.0000e+00, 1.9618e-44, 7.0065e-45]]]])


In [3]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.6026, 0.8472, 0.0414],
        [0.1983, 0.7870, 0.3825],
        [0.6563, 0.7211, 0.4996],
        [0.4738, 0.3011, 0.9224],
        [0.1675, 0.9575, 0.4061]])


In [4]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(3, 4)
y = torch.ones(2, 3)
print(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.Size([3, 4])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [6]:
# construct from data
data = [2.2, 1.6, 5.9]
x = torch.tensor([5.5, 3])
y = torch.tensor(data)
print(x)
print(x.size())
print(y)
print(y.size())

tensor([5.5000, 3.0000])
torch.Size([2])
tensor([2.2000, 1.6000, 5.9000])
torch.Size([3])


In [7]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [8]:
# Operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

In [9]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.0590, 0.7561, 0.0766],
        [0.3415, 0.5372, 0.5914],
        [0.9169, 0.2995, 0.7301],
        [0.8492, 0.7989, 0.3011],
        [0.2853, 0.4269, 0.1823]])
tensor([0.0590, 0.3415, 0.9169, 0.8492, 0.2853])
tensor([0.3415, 0.5372, 0.5914])
tensor(0.5372)


In [10]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.5372061133384705


In [11]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z1= x.view(-1, 8)  # the size -1 is inferred from other dimensions
z2= x.view(4, -1)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z1.size(), z2.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([4, 4])


In [12]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
import numpy as np

a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [13]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # default dtype is torch.float64
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)
# print(b.dtype)
# b = torch.tensor(b, dtype=torch.float32)
# print(b.dtype)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [14]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z = z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()