# Installation

To download PyTorch, go to the link: https://pytorch.org/get-started/locally/

- select OS: Linux/ Mac/ Windows
- select Package: conda
- select Python 3.7

if Linux or Windows and want GPU support
- select Cuda version 10.2/ 11.3

Install Cuda Toolkit
Development environment for creating high performance GPU-accelerated applications
You need an NVIDIA GPU in your machine:

https://developer.nvidia.com/cuda-downloads

Legacy releases
11.0 update 2
select OS (e.g. Ubuntu)

Download and install

# Create conda environment and activate it 
`$ conda create -n pytorch python=3.7`

`$ conda activate pytorch`

# Install pytorch
`$ conda install pytorch torchvision -c pytorch`

or with GPU
`$ conda install pytorch torchvision cudatoolkit=11.3 -c pytorch`

In [1]:
# Installation Verification:
import torch

if torch.cuda.is_available():
    print(f"{torch.cuda.get_device_name(0)} is available for tensor operations!")
else:
    print("GPU is unavailable!")

NVIDIA GeForce GTX 1060 6GB is available for tensor operations!


# Tensor Basics

In [2]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher
# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(f"Scaler tensor: {x}")

x = torch.empty(3) # vector, 1D
print(f"Vector tensor: {x}")

x = torch.empty(2,3) # matrix, 2D
print(f"Matrix tensor: {x}")

x = torch.empty(2,2,3) # tensor, 3 dimensions

y = torch.empty(2,2,2,3) # tensor, 4 dimensions

print(f"Tensor with 3 dimensions: {x}")
print(f"Tensor with 4 dimensions: {y}")

Scaler tensor: tensor([0.])
Vector tensor: tensor([-1.1407e-11,  3.0903e-41,  1.3575e+33])
Matrix tensor: tensor([[-1.1408e-11,  3.0903e-41,  4.4377e+27],
        [ 1.9366e+31,  8.6275e+00,  9.2851e-04]])
Tensor with 3 dimensions: tensor([[[ 1.4013e-45,  0.0000e+00, -1.1418e-11],
         [ 3.0903e-41,  1.4013e-45,  0.0000e+00]],

        [[-1.1418e-11,  3.0903e-41,  3.3631e-44],
         [ 1.3563e-19,  3.2194e+32,  4.5727e-41]]])
Tensor with 4 dimensions: tensor([[[[ 1.3575e+33,  4.5727e-41, -1.1403e-11],
          [ 3.0903e-41,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[-1.1417e-11,  3.0903e-41,  0.0000e+00],
          [ 0.0000e+00, -1.1412e-11,  3.0903e-41]],

         [[-1.1412e-11,  3.0903e-41, -1.1412e-11],
          [ 3.0903e-41,  8.4078e-45,  0.0000e+00]]]])


In [3]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.5959, 0.6974, 0.5579],
        [0.4447, 0.8369, 0.3776],
        [0.9087, 0.5347, 0.1769],
        [0.3126, 0.6809, 0.8345],
        [0.2638, 0.0277, 0.8080]])


In [4]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(3, 4)
y = torch.ones(2, 3)
print(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.Size([3, 4])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [6]:
# construct from data
data = [2.2, 1.6, 5.9]
x = torch.tensor([5.5, 3])
y = torch.tensor(data)
print(x)
print(x.size())
print(y)
print(y.size())

tensor([5.5000, 3.0000])
torch.Size([2])
tensor([2.2000, 1.6000, 5.9000])
torch.Size([3])


In [7]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [8]:
# Operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

In [9]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.8108, 0.0536, 0.0768],
        [0.8509, 0.6689, 0.4799],
        [0.3808, 0.5549, 0.9608],
        [0.7878, 0.3074, 0.3721],
        [0.5664, 0.7292, 0.0378]])
tensor([0.8108, 0.8509, 0.3808, 0.7878, 0.5664])
tensor([0.8509, 0.6689, 0.4799])
tensor(0.6689)


In [10]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.6689321398735046


In [11]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [13]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [14]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()