# PyTorch's Tensor Library

In [1]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher
# scalar, vector, matrix, tensor

import torch

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(f"Scaler tensor: {x}")

x = torch.empty(3) # vector, 1D
print(f"Vector tensor: {x}")

x = torch.empty(2,3) # matrix, 2D
print(f"Matrix tensor: {x}")

x = torch.empty(2,2,3) # tensor, 3 dimensions

y = torch.empty(2,2,2,3) # tensor, 4 dimensions

print(f"Tensor with 3 dimensions: {x}")
print(f"Tensor with 4 dimensions: {y}")

Scaler tensor: tensor([2.4618e-38])
Vector tensor: tensor([-1.3507e-20,  3.0805e-41,  4.6487e-06])
Matrix tensor: tensor([[4.6487e-06, 4.5720e-41, 4.6487e-06],
        [4.5720e-41, 4.4842e-44, 0.0000e+00]])
Tensor with 3 dimensions: tensor([[[-1.3504e-20,  3.0805e-41, -1.3504e-20],
         [ 3.0805e-41,  8.9683e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00, -6.9115e-22],
         [ 3.0805e-41,  4.6487e-06,  4.5720e-41]]])
Tensor with 4 dimensions: tensor([[[[ 4.6488e-06,  4.5720e-41,  4.6488e-06],
          [ 4.5720e-41,  1.4013e-45,  0.0000e+00]],

         [[ 1.4013e-45,  0.0000e+00,  1.4013e-45],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 8.9683e-44,  0.0000e+00,  8.9683e-44],
          [ 0.0000e+00, -1.3497e-20,  3.0805e-41]],

         [[ 4.6487e-06,  4.5720e-41,  4.0357e-43],
          [ 0.0000e+00,  1.1210e-43,  0.0000e+00]]]])


In [2]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.5674, 0.8914, 0.6147],
        [0.2194, 0.9691, 0.3777],
        [0.4788, 0.7643, 0.4240],
        [0.2587, 0.4929, 0.1503],
        [0.0815, 0.4421, 0.7711]])


In [3]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(3, 4)
y = torch.ones(2, 3)
print(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.Size([3, 4])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [5]:
# construct from data
data = [2.2, 1.6, 5.9]
x = torch.tensor([5.5, 3])
y = torch.tensor(data)
print(x)
print(x.size())
print(y)
print(y.size())

tensor([5.5000, 3.0000])
torch.Size([2])
tensor([2.2000, 1.6000, 5.9000])
torch.Size([3])


In [6]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [7]:
# Operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

In [8]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.1503, 0.9595, 0.1726],
        [0.8458, 0.0665, 0.4991],
        [0.6215, 0.8518, 0.4204],
        [0.3687, 0.1026, 0.9599],
        [0.7674, 0.3754, 0.7562]])
tensor([0.1503, 0.8458, 0.6215, 0.3687, 0.7674])
tensor([0.8458, 0.0665, 0.4991])
tensor(0.0665)


In [9]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.06651777029037476


In [10]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z1= x.view(-1, 8)  # the size -1 is inferred from other dimensions
z2= x.view(4, -1)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z1.size(), z2.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([4, 4])


In [11]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
import numpy as np

a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [12]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # default dtype is torch.float64
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)
# print(b.dtype)
# b = torch.tensor(b, dtype=torch.float32)
# print(b.dtype)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [13]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z = z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()