In [1]:
import torch
if torch.cuda.is_available():
    print("GPU activated!")
else:
    print("No GPU, sorry!")

GPU activated!


In [2]:
print(torch.cuda.is_available())

True


# torch.mm()

In [3]:
import torch
  
mat_1 = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
  
mat_2 = torch.tensor([[3, 2, 1],
                      [6, 5, 4],
                      [9, 8, 7]])
  
result = torch.mm(mat_1, mat_2, out=None)
print(result)

tensor([[ 42,  36,  30],
        [ 96,  81,  66],
        [150, 126, 102]])


In [4]:
mat_1 = torch.tensor([[5, 4],
                      [3, 1]])
  
mat_2 = torch.tensor([[4, 5, 6],
                      [3, 2, 9]])
  
result = torch.mm(mat_1, mat_2, out=None)
print(result)

tensor([[32, 33, 66],
        [15, 17, 27]])


# torch.matmul()

In [5]:
# Both arguments in 1D
vec_1 = torch.tensor([1, 3, 9])
vec_2 = torch.tensor([2, 4, 6])
  
print("1 dimensional tensors :", torch.matmul(vec_1, vec_2))
  
# Both arguments in 2D
mat_1 = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
  
mat_2 = torch.tensor([[3, 2, 1],
                      [4, 5, 6],
                      [9, 3, 5]])
  
out = torch.matmul(mat_1, mat_2)
  
print("\n3x3 dimensional tensors :\n", out)

1 dimensional tensors : tensor(68)

3x3 dimensional tensors :
 tensor([[ 38,  21,  28],
        [ 86,  51,  64],
        [134,  81, 100]])


In [6]:
# first argument is a 1D tensor and second argument is a 2D tensor
mat1_1 = torch.tensor([4, 8, 12])
  
mat1_2 = torch.tensor([[6, 3, 2],
                       [4, 7, 9],
                       [1, 3, 8]])

# assigning to output tensor
out_1 = torch.matmul(mat1_1, mat1_2)
print("\n1D-2D multiplication :\n", out_1)
  
# first argument is a 2D tensor and second argument is a 1D tensor
mat2_1 = torch.tensor([[5, 4, 9],
                       [8, 2, 6],
                       [1, 3, 7]])
  
mat2_2 = torch.tensor([8, 3, 5])
  
# assigning to output tensor
out_2 = torch.matmul(mat2_1, mat2_2)
  
print("\n2D-1D multiplication :\n", out_2)


1D-2D multiplication :
 tensor([ 68, 104, 176])

2D-1D multiplication :
 tensor([ 97, 100,  52])


In [7]:
# Creating tensors using randn()
mat_1 = torch.randn(2, 3, 3)
mat_2 = torch.randn(3)
  
# printing the matrices
print("matrix A:\n", mat_1)
print("\nmatrix B:\n", mat_2)
  
# output
print("\nOutput:\n", torch.matmul(mat_1, mat_2))

matrix A:
 tensor([[[ 0.8791,  0.4386,  1.5736],
         [ 2.0985,  0.7290, -1.2222],
         [ 1.2666,  1.0298,  0.7199]],

        [[-0.9066,  0.7193,  0.8705],
         [ 2.0638, -0.2563,  0.7273],
         [ 0.6730,  1.9980, -0.3497]]])

matrix B:
 tensor([-0.6926, -0.2329, -0.0610])

Output:
 tensor([[-0.8071, -1.5487, -1.1611],
        [ 0.4073, -1.4141, -0.9102]])


# torch.bmm()

In [8]:
# 3D matrices
mat_1 = torch.randn(2, 3, 3)
mat_2 = torch.randn(2, 3, 4)
  
print("matrix A:\n",mat_1)
print("\nmatrix B:\n",mat_2)
  
print("\nOutput:\n",torch.bmm(mat_1,mat_2))

matrix A:
 tensor([[[ 0.7175,  0.1087, -1.4721],
         [ 1.3329,  2.5658,  0.7460],
         [-0.0374,  0.1123, -0.3050]],

        [[ 0.0235,  1.4923, -0.3238],
         [ 0.9407,  0.5569,  0.6364],
         [ 0.4625, -0.0409,  0.3578]]])

matrix B:
 tensor([[[-0.7249, -1.2981,  0.8067, -0.1779],
         [ 0.3844, -0.3646,  0.3373,  0.7014],
         [-0.7754,  0.2107,  0.0608, -0.0081]],

        [[ 2.1600, -0.5071, -2.1004, -0.5750],
         [-0.8392,  0.2148, -0.0936, -0.1812],
         [ 0.5169, -0.6990,  0.8720, -0.7427]]])

Output:
 tensor([[[ 0.6631, -1.2812,  0.5260, -0.0394],
         [-0.5585, -2.5086,  1.9860,  1.5564],
         [ 0.3068, -0.0566, -0.0109,  0.0879]],

        [[-1.3690,  0.5350, -0.4714, -0.0434],
         [ 1.8936, -0.8023, -1.4731, -1.1146],
         [ 1.2183, -0.4935, -0.6556, -0.5243]]])


# @ operator

In [9]:
# 1 dimensional matrices
oneD_1 = torch.tensor([4, 2, 8])
oneD_2 = torch.tensor([7, 5, 9])
  
  
# 2 dimensional matrices
twoD_1 = torch.tensor([[3, 2, 1],
                       [7, 3, 9],
                       [8, 7, 3]])
twoD_2 = torch.tensor([[1, 5, 7],
                       [6, 8, 9],
                       [3, 5, 2]])
  
# N-dimensional matrices (N>2)
  
# 2x3x3 dimensional matrix
ND_1 = torch.tensor([[[-1.3063, -0.2510,  0.9827],
                      [-0.5879, -1.3373,  0.3768],
                      [-1.2140, -1.5296, -1.0637]],

                     [[ 1.2284,  0.7159,  1.0088],
                      [-2.0181,  1.7579, -0.7130],
                      [-0.1003,  0.9969, -0.7118]]])
  
# 2x3x4 dimensional matrix
ND_2 = torch.tensor([[[-2.4476,  0.1451, -0.1343, -0.0566],
                      [-0.6806, -0.3490,  0.9293,  1.3008],
                      [-1.8136, -0.4449, -1.4303, -1.4246]],

                     [[ 1.9980, -0.9932,  0.0822, -1.9171],
                      [ 1.1568, -1.6384, -0.5876,  0.4152],
                      [ 1.9009, -0.4793,  2.6457,  0.2506]]])
  
print("Output of 1D matrices:\n", oneD_1 @ oneD_2)
print("\nOutput of 2D matrices:\n", twoD_1 @ twoD_2)
print("\nOutput of N-D matrices:\n", ND_1 @ ND_2)
print("\n Output of Mixed matrices:\n", oneD_1 @ twoD_1 @ twoD_2)

Output of 1D matrices:
 tensor(110)

Output of 2D matrices:
 tensor([[ 18,  36,  41],
        [ 52, 104,  94],
        [ 59, 111, 125]])

Output of N-D matrices:
 tensor([[[ 1.5859, -0.5391, -1.4634, -1.6525],
         [ 1.6657,  0.2138, -1.7027, -2.2431],
         [ 5.9416,  0.8309,  0.2630, -0.4056]],

        [[ 5.2001, -2.8765,  2.3493, -1.8049],
         [-3.3540, -0.5340, -3.0852,  4.4201],
         [-0.4002, -1.1925, -2.4772,  0.4278]]])

 Output of Mixed matrices:
 tensor([ 648, 1240, 1352])


# torch.mul()

In [10]:
# torch.mul() to perform element-wise multiplication
import torch

# Create a tensor
t = torch.Tensor([3.67, 8.45, 7.43, 2.89])
print("Original Tensor t:\n", t)

# Way -1: Multiply a scalar value to a tensor
v = torch.mul(t, 5)
print("Element-wise multiplication result:\n", v)

# Way -2: Same result can also be obtained as below
t1 = torch.Tensor([5])
w = torch.mul(t, t1)
print("Element-wise multiplication result:\n", w)

# Way -3: Other way to do above operation
t2 = torch.Tensor([5,5,5,5])
x = torch.mul(t, t2)
print("Element-wise multiplication result:\n", x)

Original Tensor t:
 tensor([3.6700, 8.4500, 7.4300, 2.8900])
Element-wise multiplication result:
 tensor([18.3500, 42.2500, 37.1500, 14.4500])
Element-wise multiplication result:
 tensor([18.3500, 42.2500, 37.1500, 14.4500])
Element-wise multiplication result:
 tensor([18.3500, 42.2500, 37.1500, 14.4500])


In [11]:
# Create a 2D tensor
T1 = torch.Tensor([[5,4],[3,8]])

# Create a 1D tensor
T2 = torch.Tensor([4, 7])
print("T1:\n", T1)
print("T2:\n", T2)

# Multiply 1-D tensor with 2-D tensor
v = torch.mul(T1, T2) # v = torch.mul(T2,T1)
print("Element-wise multiplication result:\n", v)

T1:
 tensor([[5., 4.],
        [3., 8.]])
T2:
 tensor([4., 7.])
Element-wise multiplication result:
 tensor([[20., 28.],
        [12., 56.]])


In [12]:
# Create two 2D tensors
T1 = torch.Tensor([[5,3],[2,1]])
T2 = torch.Tensor([[6,8],[1,4]])
print("T1:\n", T1)
print("T2:\n", T2)

# Multiply above two 2D tensors
v = torch.mul(T1,T2)
print("Element-wise subtraction result:\n", v)

T1:
 tensor([[5., 3.],
        [2., 1.]])
T2:
 tensor([[6., 8.],
        [1., 4.]])
Element-wise subtraction result:
 tensor([[30., 24.],
        [ 2.,  4.]])
