In [4]:
import torch
if torch.cuda.is_available():
    print("GPU activated!")
else:
    print("No GPU, sorry!")

GPU activated!


In [6]:
print(torch.cuda.is_available())

True


# torch.mm()

In [9]:
import torch
  
mat_1 = torch.tensor([[1, 2, 3],
                      [4, 3, 8],
                      [1, 7, 2]])
  
mat_2 = torch.tensor([[2, 4, 1],
                      [1, 3, 6],
                      [2, 6, 5]])
  
result = torch.mm(mat_1, mat_2, out=None)
print(result)

tensor([[10, 28, 28],
        [27, 73, 62],
        [13, 37, 53]])


In [11]:
mat_1 = torch.tensor([[1, 2],
                      [4, 3]])
  
mat_2 = torch.tensor([[2, 4, 1],
                      [1, 3, 6]])
  
result = torch.mm(mat_1, mat_2, out=None)
print(result)

tensor([[ 4, 10, 13],
        [11, 25, 22]])


# torch.matmul()

In [12]:
# both arguments 1D
vec_1 = torch.tensor([3, 6, 2])
vec_2 = torch.tensor([4, 1, 9])
  
print("Single dimensional tensors :", torch.matmul(vec_1, vec_2))
  
# both arguments 2D
mat_1 = torch.tensor([[1, 2, 3],
                      [4, 3, 8],
                      [1, 7, 2]])
  
mat_2 = torch.tensor([[2, 4, 1],
                      [1, 3, 6],
                      [2, 6, 5]])
  
out = torch.matmul(mat_1, mat_2)
  
print("\n3x3 dimensional tensors :\n", out)

Single dimensional tensors : tensor(36)

3x3 dimensional tensors :
 tensor([[10, 28, 28],
        [27, 73, 62],
        [13, 37, 53]])


In [13]:
# first argument 1D and second argument 2D
mat1_1 = torch.tensor([3, 6, 2])
  
mat1_2 = torch.tensor([[1, 2, 3],
                       [4, 3, 8],
                       [1, 7, 2]])
  
out_1 = torch.matmul(mat1_1, mat1_2)
print("\n1D-2D multiplication :\n", out_1)
  
# first argument 2D and second argument 1D
mat2_1 = torch.tensor([[2, 4, 1],
                       [1, 3, 6],
                       [2, 6, 5]])
  
mat2_2 = torch.tensor([4, 1, 9])
  
# assigning to output tensor
out_2 = torch.matmul(mat2_1, mat2_2)
  
print("\n2D-1D multiplication :\n", out_2)


1D-2D multiplication :
 tensor([29, 38, 61])

2D-1D multiplication :
 tensor([21, 61, 59])


In [14]:
# creating Tensors using randn()
mat_1 = torch.randn(2, 3, 3)
mat_2 = torch.randn(3)
  
# printing the matrices
print("matrix A :\n", mat_1)
print("\nmatrix B :\n", mat_2)
  
# output
print("\nOutput :\n", torch.matmul(mat_1, mat_2))

matrix A :
 tensor([[[ 1.0489, -0.4715, -0.1354],
         [-1.6237, -2.3288, -0.1502],
         [-0.9784,  0.4239, -0.0952]],

        [[ 2.2182,  0.8941, -0.1166],
         [ 1.1528,  1.2465, -0.6772],
         [ 1.4247,  1.1962,  0.1975]]])

matrix B :
 tensor([ 1.9160, -0.7550, -0.4061])

Output :
 tensor([[ 2.4207, -1.2917, -2.1561],
        [ 3.6225,  1.5428,  1.7464]])


# torch.bmm()

In [15]:
# 3D matrices
mat_1 = torch.randn(2, 3, 3)
mat_2 = torch.randn(2, 3, 4)
  
print("matrix A :\n",mat_1)
print("\nmatrix B :\n",mat_2)
  
print("\nOutput :\n",torch.bmm(mat_1,mat_2))

matrix A :
 tensor([[[ 0.2582, -1.7416, -0.1094],
         [-1.4233,  0.6656,  1.6345],
         [ 0.0192,  0.7255, -1.3925]],

        [[-0.1162, -1.6027, -1.0653],
         [ 0.8615,  0.3176,  0.3048],
         [-0.4855,  0.9459, -1.2246]]])

matrix B :
 tensor([[[ 0.4430, -0.8563, -0.7656, -0.2774],
         [-0.6127,  0.8453, -0.1593,  0.4870],
         [ 0.5344,  1.2098,  0.0248, -0.9675]],

        [[ 0.2728,  1.4921, -1.2494,  1.2886],
         [-0.2100,  0.0187,  0.3796,  0.6974],
         [-0.0662, -0.6768, -0.3913,  1.2506]]])

Output :
 tensor([[[ 1.1229, -1.8257,  0.0771, -0.8139],
         [-0.1649,  3.7588,  1.0242, -0.8623],
         [-1.1802, -1.0877, -0.1648,  1.6952]],

        [[ 0.3755,  0.5177, -0.0463, -2.5996],
         [ 0.1481,  1.0850, -1.0750,  1.7128],
         [-0.2500,  0.1222,  1.4447, -1.4973]]])


# @ operator

In [16]:
# single dimensional matrices
oneD_1 = torch.tensor([3, 6, 2])
oneD_2 = torch.tensor([4, 1, 9])
  
  
# two dimensional matrices
twoD_1 = torch.tensor([[1, 2, 3],
                       [4, 3, 8],
                       [1, 7, 2]])
twoD_2 = torch.tensor([[2, 4, 1],
                       [1, 3, 6],
                       [2, 6, 5]])
  
# N-dimensional matrices (N>2)
  
# 2x3x3 dimensional matrix
ND_1 = torch.tensor([[[-0.0135, -0.9197, -0.3395],
                      [-1.0369, -1.3242,  1.4799],
                      [-0.0182, -1.2917,  0.6575]],
  
                     [[-0.3585, -0.0478,  0.4674],
                      [-0.6688, -0.9217, -1.2612],
                      [1.6323, -0.0640,  0.4357]]])
  
# 2x3x4 dimensional matrix
ND_2 = torch.tensor([[[0.2431, -0.1044, -0.1437, -1.4982],
                      [-1.4318, -0.2510,  1.6247,  0.5623],
                      [1.5265, -0.8568, -2.1125, -0.9463]],
  
                     [[0.0182,  0.5207,  1.2890, -1.3232],
                      [-0.2275, -0.8006, -0.6909, -1.0108],
                      [1.3881, -0.0327, -1.4890, -0.5550]]])
  
print("1D matrices output :\n", oneD_1 @ oneD_2)
print("\n2D matrices output :\n", twoD_1 @ twoD_2)
print("\nN-D matrices output :\n", ND_1 @ ND_2)
print("\n Mixed matrices output :\n", oneD_1 @ twoD_1 @ twoD_2)

1D matrices output :
 tensor(36)

2D matrices output :
 tensor([[10, 28, 28],
        [27, 73, 62],
        [13, 37, 53]])

N-D matrices output :
 tensor([[[ 0.7953,  0.5231, -0.7751, -0.1757],
         [ 3.9030, -0.8274, -5.1287, -0.5915],
         [ 2.8487, -0.2372, -3.4850, -1.3212]],

        [[ 0.6531, -0.1637, -1.1250,  0.2633],
         [-1.5532,  0.4309,  1.6526,  2.5166],
         [ 0.6491,  0.8869,  1.4995, -2.3370]]])

 Mixed matrices output :
 tensor([218, 596, 562])


# torch.mul()