# PyTorch's Tensor Library

In [2]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher
# scalar, vector, matrix, tensor

import torch

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(f"Scaler tensor: {x}")

x = torch.empty(3) # vector, 1D
print(f"Vector tensor: {x}")

x = torch.empty(2,3) # matrix, 2D
print(f"Matrix tensor: {x}")

x = torch.empty(2,2,3) # tensor, 3 dimensions

y = torch.empty(2,2,2,3) # tensor, 4 dimensions

print(f"Tensor with 3 dimensions: {x}")
print(f"Tensor with 4 dimensions: {y}")

Scaler tensor: tensor([1.0006e-34])
Vector tensor: tensor([-4.6314e-26,  3.0815e-41, -2.2937e-27])
Matrix tensor: tensor([[-4.6000e-26,  3.0815e-41, -4.6294e-26],
        [ 3.0815e-41, -1.7546e+38,  2.4641e-38]])
Tensor with 3 dimensions: tensor([[[-4.5899e-26,  3.0815e-41,  0.0000e+00],
         [ 0.0000e+00,  1.8888e+31,  2.0196e-19]],

        [[ 6.1188e-04,  4.8419e+30,  1.8389e+25],
         [ 1.9007e-19,  6.5610e+05,  1.6611e+22]]])
Tensor with 4 dimensions: tensor([[[[-8.4484e-13,  4.5640e-41, -8.4484e-13],
          [ 4.5640e-41,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[-2.2938e-27,  3.0815e-41,  0.0000e+00],
          [ 0.0000e+00, -4.5888e-26,  3.0815e-41]],

         [[-4.5888e-26,  3.0815e-41, -4.5888e-26],
          [ 3.0815e-41,  0.0000e+00,  0.0000e+00]]]])


In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

In [ ]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(3, 4)
y = torch.ones(2, 3)
print(x)
print(y)

In [ ]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

In [ ]:
# construct from data
data = [2.2, 1.6, 5.9]
x = torch.tensor([5.5, 3])
y = torch.tensor(data)
print(x)
print(x.size())
print(y)
print(y.size())

In [ ]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

In [ ]:
# Operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

In [18]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.1522, 0.9029, 0.8695],
        [0.0981, 0.3290, 0.8080],
        [0.5859, 0.3518, 0.9628],
        [0.2238, 0.8474, 0.7816],
        [0.5466, 0.0633, 0.1578]])
tensor([0.1522, 0.0981, 0.5859, 0.2238, 0.5466])
tensor([0.0981, 0.3290, 0.8080])
tensor(0.3290)


In [19]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.32895803451538086


In [20]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z1= x.view(-1, 8)  # the size -1 is inferred from other dimensions
z2= x.view(4, -1)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z1.size(), z2.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([4, 4])


In [22]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
import numpy as np

a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # default dtype is torch.float64
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)
# print(b.dtype)
# b = torch.tensor(b, dtype=torch.float32)
# print(b.dtype)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z = z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

In [5]:
torch.manual_seed(101)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(101)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])
tensor([[0.9095, 0.3406, 0.4309],
        [0.7324, 0.4776, 0.0716]])
tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])
tensor([[0.9095, 0.3406, 0.4309],
        [0.7324, 0.4776, 0.0716]])


In [6]:
torch.manual_seed(101)
random = torch.rand(2, 3)
print(random)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])


In [7]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-8.4483e-13,  4.5640e-41, -4.5903e-26],
         [ 3.0815e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00, -4.5903e-26],
         [ 3.0815e-41,  4.2039e-45,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-8.4483e-13,  4.5640e-41, -8.4483e-13],
         [ 4.5640e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  4.2039e-45,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.9095, 0.3406, 0.4309],
         [0.7324, 0.4776, 0.0716]],

        [[0.5834, 0.7521, 0.7649],
         [0.1443, 0.7152, 0.3953]]])


In [9]:
some_constants = torch.tensor([[9.67664, 7.56828], [3.45603, 2.06879]])
print(some_constants)

some_integers = torch.tensor((3, 2, 6, 1, 31, 43, 19, 27))
print(some_integers)

more_integers = torch.tensor(((1, 3, 6), [6, 3, 7]))
print(more_integers)

tensor([[9.6766, 7.5683],
        [3.4560, 2.0688]])
tensor([ 3,  2,  6,  1, 31, 43, 19, 27])
tensor([[1, 3, 6],
        [6, 3, 7]])


In [11]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64)
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[0.8603, 0.1338, 0.0672],
        [0.9772, 0.7371, 0.5074]], dtype=torch.float64)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [12]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [13]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [14]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [16]:
import math
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.6551, 0.6402, 0.6651, 0.0202],
        [0.1011, 0.9940, 0.8729, 0.1500]])
tensor([[1., -0., -0., 1.],
        [-0., -0., 1., -0.]])
tensor([[ 0., -1., -1.,  0.],
        [-1., -1.,  0., -1.]])
tensor([[ 0.5000, -0.5000, -0.5000,  0.0202],
        [-0.1011, -0.5000,  0.5000, -0.1500]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9697, 0.3714],
        [0.4656, 0.9026]])
tensor([[2.9091, 1.1141],
        [1.3967, 2.7078]])
torch.return_types.svd(
U=tensor([[-0.7175, -0.6965],
        [-0.6965,  0.7175]]),
S=tensor([4.0714, 1.5526]),
V=tensor([[-0.7516, -0.6596],
        [-0.6596,  0.7516]]))


In [17]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5511, 0.9323],
        [0.7693, 0.8898]])

After adding:
tensor([[1.5511, 1.9323],
        [1.7693, 1.8898]])
tensor([[1.5511, 1.9323],
        [1.7693, 1.8898]])
tensor([[0.5511, 0.9323],
        [0.7693, 0.8898]])

After multiplying
tensor([[0.3037, 0.8691],
        [0.5919, 0.7917]])
tensor([[0.3037, 0.8691],
        [0.5919, 0.7917]])


In [23]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

We have a GPU!


In [24]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.6941, 0.0714],
        [0.3151, 0.0764]], device='cuda:0')


In [26]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print(f'Device: {my_device}')

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.0706, 0.6300],
        [0.4767, 0.5797]], device='cuda:0')


In [27]:
y = torch.rand(2, 2)
y = y.to(my_device)